bot:
  token: "скинул тебе в личку"
  group_chat_id: 'должно быть числом вида -1002425644297, замени на айди группы, в которой будет бот'
  admin_chat_id: 618628269  # Это мой айди, можешь поменять на свой, если хочешь